### ISSUE TITLE
pipeline validation failed

### ISSUE THREAD

**Issue by omerb01** [metaspace2020/pywren-annotation-pipeline#65]
I cleaned my bucket from all tmp objects that we store during the process and after rerunning the workload, I observe the following: (on "big" dataset with "experiment 1" notebook)
```
2020-04-23 10:40:49,041 [INFO] annotation-pipeline: Missing annotations: 0 (PASS)
2020-04-23 10:40:49,042 [ERROR] annotation-pipeline: Incorrect spatial metric: 2 (FAIL)
2020-04-23 10:40:49,043 [INFO] annotation-pipeline: Incorrect spectral metric: 4 (PASS)
2020-04-23 10:40:49,044 [INFO] annotation-pipeline: Incorrect chaos metric: 0 (PASS)
2020-04-23 10:40:49,045 [ERROR] annotation-pipeline: Incorrect MSM: 2 (FAIL)
2020-04-23 10:40:49,046 [INFO] annotation-pipeline: FDR changed: 131 (PASS)
2020-04-23 10:40:49,047 [INFO] annotation-pipeline: FDR changed significantly: 0 (PASS)
2020-04-23 10:40:49,050 [ERROR] annotation-pipeline: Incorrect spatial metric extra info:
          spatial  spatial_ref     error
ion_i                                   
634513   0.444191     0.450914  0.006723
2291558  0.010216     0.011723  0.001507

2020-04-23 10:40:49,053 [ERROR] annotation-pipeline: Incorrect MSM extra info:
              msm   msm_ref     error
ion_i                                
634513   0.401638  0.408331  0.006693
2291558  0.009076  0.010549  0.001473

2020-04-23 10:40:49,054 [ERROR] annotation-pipeline: 2 checks failed
```
I tried to rebase the project based on previous PRs, it seems that this issue still happens on PR #60 and I can't test previous PRs than that cause I don't have the old pickles anymore.

@LachlanStuart what do you think? can you try also to clean all objects under prefix: `metabolomics/tmp` ? to find out if you observe the same issue.

**Comment by LachlanStuart** [comment]
@omerb01 I've done some preliminary investigation, and it seems that this isn't the fault of pywren-annotation-pipeline. That dataset was reprocessed on METASPACE on April 8th, and those two annotations changed on the METASPACE server.

The reason they changed seems to be because they both only have 3 images instead of the usual 4. I know METASPACE had a change (I think back in 2018) which changed the spatial metric slightly for those cases. I thought that that dataset had been processed after that fix, but I must have been wrong. 

As far as I can tell, the current pywren-annotation-pipeline code looks almost identical to the current METASPACE code, so I'm not sure why pywren-annotation-pipeline is using the old behavior for annotations that have fewer than 4 images, instead of the new behavior.

As this bug is in part of the business logic, it would be my responsibility to fix. However, because this is just a minor data bug, and doesn't reflect any problems or changed behavior in the overall pipeline, I'd like to hold off on fixing it as it could take quite a bit of time. Will it cause any disruption for you if I wait until later to fix this? 

If you'd like the test to pass again, we could raise the [acceptable threshold for spatial and MSM errors](https://github.com/metaspace2020/pywren-annotation-pipeline/blob/master/annotation_pipeline/check_results.py#L88) to 2, because we now know the cause.

**Comment by omerb01** [comment]
@LachlanStuart thanks, it's ok to hold it for a while. I think your suggestion about the threshold can come in handy since we need some kind of feedback that will tell us if we mistakenly broke the code.

**Comment by gilv** [comment]
@omerb01 what is the status of it?

**Comment by omerb01** [comment]
@gilv haven't been solved yet, the"big" dataset has some incorrectness
