### ISSUE TITLE
Python 3.6 requirement

### ISSUE THREAD

**Issue by gilv** [metaspace2020/pywren-annotation-pipeline#75]
Any particular reason we have 

assert (3, 6) <= sys.version_info < (3, 7), 'Python 3.6 is required'

@LachlanStuart ?

**Comment by LachlanStuart** [comment]
It's there for safety, because the host and function runtimes must use the same version. If we change Python version, we should update that to enforce the new version.

We originally wanted to stick to 3.6 to match production METASPACE. However, we have discussed it internally since then, and don't feel that there is a strict need to keep them the same. I'm happy if this project is moved to a newer version of Python.

**Comment by gilv** [comment]
@LachlanStuart then i can greatly try it with Python 3.7.5 and if all works smooth, i will create new runtime for 3.7.5
@omerb01 any objections?

**Comment by omerb01** [comment]
@gilv Nope :) i think that its a great direction
